image: ubuntu:latest

variables:
  EMSDK_TAG: 1.39.13
  QT_BRANCH: 5.15.0

sdl:
  script:
    - apt-get update
    - apt-get install -y automake autoconf git python xz-utils bzip2 libtool make libicu-dev libxml2 curl libtolua-dev
    - git clone https://github.com/emscripten-core/emsdk /emsdk
    - /emsdk/emsdk install $EMSDK_TAG
    - /emsdk/emsdk activate $EMSDK_TAG
    - source /emsdk/emsdk_env.sh
    - emconfigure ./autogen.sh --enable-client=sdl2 --disable-nls
    - emmake make
  artifacts:
    paths:
    - client/freeciv-sdl2.data
    - client/freeciv-sdl2.html
    - client/freeciv-sdl2.js
    - client/freeciv-sdl2.wasm

qt:
  script:
    - apt-get update
    - apt-get install -y automake autoconf git python xz-utils bzip2 libtool make libicu-dev libxml2 curl libtolua-dev
    - git clone https://github.com/emscripten-core/emsdk /emsdk
    - /emsdk/emsdk install $EMSDK_TAG
    - /emsdk/emsdk activate $EMSDK_TAG
    - source /emsdk/emsdk_env.sh
    - git clone https://github.com/qt/qtbase /qtbase --depth=1 --branch=${QT_BRANCH}
    - pushd /qtbase
    - ./configure -xplatform wasm-emscripten -nomake examples -prefix /qt5 -opensource -confirm-license
    - make install
    - popd
    - emconfigure ./autogen.sh --enable-client=qt --disable-nls --with-qt5=/qt5
    - emmake make
  cache:
    key: qt_${EMSDK_TAG}_${QT_BRANCH}
    paths:
    - qtbase/
  artifacts:
    paths:
    - client/freeciv-qt.data
    - client/freeciv-qt.js
    - client/freeciv-qt.wasm
