variables:
  qt_branch: 5.15.0

jobs:
- job: QtWasm
  pool:
    vmImage: 'ubuntu-latest'

  variables:
    emsdk_tag: 1.39.13
  timeoutInMinutes: 180
  steps:
  - task: Cache@2
    inputs:
      key: wasm_qt | "$(emsdk_tag)" | "$(qt_branch)"
      path: $(Build.SourcesDirectory)/qt5
      cacheHitVar: WASM_QT_CACHE_RESTORED
    displayName: 'Qt cache'

  - script: |
      nproc
      sudo apt-get update
      sudo apt-get install -y --reinstall ca-certificates
      DEBIAN_FRONTEND=noninteractive sudo apt-get install --no-install-recommends -y pkg-config g++ automake autoconf git python3 python3-distutils xz-utils bzip2 libtool make libicu-dev libxml2 curl libtolua-dev
      git clone https://github.com/emscripten-core/emsdk
      ./emsdk/emsdk install $(EMSDK_TAG)
      ./emsdk/emsdk activate $(EMSDK_TAG)
    displayName: 'Setup Build Environment'

  - script: |
      source ./emsdk/emsdk_env.sh
      git clone https://github.com/qt/qtbase qtbase --depth=1 --branch=$(QT_BRANCH)
      mkdir -p qtbuild
      pushd qtbuild
      ../qtbase/configure -xplatform wasm-emscripten -nomake examples -prefix $(Build.SourcesDirectory)/qt5 -opensource -confirm-license
      make install -j$(nproc)
      popd
    timeoutInMinutes: 120
    condition: ne(variables.WASM_QT_CACHE_RESTORED, 'true')
    displayName: 'Build Qt'

  - script: |
      source ./emsdk/emsdk_env.sh
      emconfigure ./autogen.sh --enable-client=qt --disable-nls --with-qmake=$(Build.SourcesDirectory)/qt5/bin/qmake
      emmake make -j$(nproc)
    displayName: 'Build Freeciv'

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)'
      contents: 'client/?(*.html|*.data|*.js|*.wasm)'
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: qtwasm

- job: QtWasmCMake
  pool:
    vmImage: 'ubuntu-latest'

  variables:
    emsdk_tag: 1.39.13
  timeoutInMinutes: 180
  steps:
  - task: Cache@2
    inputs:
      key: wasm_qt | "$(emsdk_tag)" | "$(qt_branch)"
      path: $(Build.SourcesDirectory)/qt5
      cacheHitVar: WASM_QT_CACHE_RESTORED
    displayName: 'Qt cache'

  - script: |
      nproc
      sudo apt-get update
      sudo apt-get install -y --reinstall ca-certificates
      DEBIAN_FRONTEND=noninteractive sudo apt-get install --no-install-recommends -y pkg-config g++ cmake git python3 python3-distutils xz-utils bzip2 libtool make libicu-dev libxml2 curl libtolua-dev
      git clone https://github.com/emscripten-core/emsdk
      ./emsdk/emsdk install $(EMSDK_TAG)
      ./emsdk/emsdk activate $(EMSDK_TAG)
    displayName: 'Setup Build Environment'

  - script: |
      source ./emsdk/emsdk_env.sh
      git clone https://github.com/qt/qtbase qtbase --depth=1 --branch=$(QT_BRANCH)
      mkdir -p qtbuild
      pushd qtbuild
      ../qtbase/configure -xplatform wasm-emscripten -nomake examples -prefix $(Build.SourcesDirectory)/qt5 -opensource -confirm-license
      make install -j$(nproc)
      popd
    timeoutInMinutes: 120
    condition: ne(variables.WASM_QT_CACHE_RESTORED, 'true')
    displayName: 'Build Qt'

  - script: |
      source ./emsdk/emsdk_env.sh
      mkdir build
      cd build
      emcmake cmake .. -DCMAKE_TOOLCHAIN_FILE=../emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DQt5_DIR=../qt5/lib/cmake/Qt5/ -DQt5Widgets_DIR=../qt5/lib/cmake/Qt5Widgets -DQt5Gui_DIR=../qt5/lib/cmake/Qt5Gui -DQt5Core_DIR=../qt5/lib/cmake/Qt5Core -DQt5Network_DIR=../qt5/lib/cmake/Qt5Network -DQt5EventDispatcherSupport_DIR=../qt5/lib/cmake/Qt5EventDispatcherSupport -DQt5FontDatabaseSupport_DIR=../qt5/lib/cmake/Qt5FontDatabaseSupport -DQt5EglSupport_DIR=../qt5/lib/cmake/Qt5EglSupport
      emmake make -j$(nproc)
    displayName: 'Build Freeciv'

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)/build'
      contents: 'client/?(*.html|*.data|*.js|*.wasm)'
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: qtwasmcmake

- job: MacOS
  pool:
    vmImage: 'macos-10.14'

  variables:
    macosx_deployment_target: 10.10

  steps:
  - task: Cache@2
    inputs:
      key: macos_qt | "$(qt_branch)" | "$(macosx_deployment_target)"
      path: $(Build.SourcesDirectory)/qt5
      cacheHitVar: MACOS_QT_CACHE_RESTORED
    displayName: 'Qt cache'

  - script: |
      find /Applications/Xcode_11.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
      which libtool || true
      libtool -version || true
      which glibtool || true
      glibtool --version || true
      brew install gettext icu4c automake autoconf sdl2_mixer pkg-config
    displayName: 'Setup Build Environment'

  - script: |
      git clone https://github.com/qt/qtbase qtbase --depth=1 --branch=$(QT_BRANCH)
      mkdir -p qtbuild
      pushd qtbuild
      ../qtbase/configure -static -nomake examples -prefix $(Build.SourcesDirectory)/qt5 -opensource -confirm-license
      make install -j$(nproc)
      popd
    timeoutInMinutes: 120
    condition: ne(variables.MACOS_QT_CACHE_RESTORED, 'true')
    displayName: 'Build Qt'

  - script: |
      cd macos
      $(Build.SourcesDirectory)/qt5/bin/qmake
      V=1 make
      cd ..
      cp -r macos $(Build.ArtifactStagingDirectory)
    displayName: 'Build test binary'

  - script: |
      export PATH="/usr/local/opt/icu4c/bin:/usr/local/opt/gettext/bin:$PATH"
      ./autogen.sh --no-configure-run
      ./configure CC="clang" CXX="clang++" PKG_CONFIG_PATH="/usr/local/opt/icu4c/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig:/usr/local/lib/pkgconfig" CFLAGS="-O3 -I/usr/local/opt/gettext/include" LDFLAGS="-L/usr/local/opt/gettext/lib" --enable-client=qt --disable-fcmp --enable-fcdb=sqlite3 --prefix=/usr/local --with-qmake=$(Build.SourcesDirectory)/qt5/bin/qmake
      V=1 make || true
      mkdir staging || true
      cp client/freeciv-qt server/freeciv-server staging || true
      cd staging || true
      $(Build.SourcesDirectory)/qt5/bin/macdeployqt -dmg FreecivQt.app || true
    displayName: 'Build Freeciv'

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)'
      contents: 'config.log'
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: macos

- job: QtWindows
  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - task: Cache@2
    inputs:
      key: win_qt | "$(qt_branch)"
      path: $(Build.SourcesDirectory)/qt5
      cacheHitVar: WIN_QT_CACHE_RESTORED
    displayName: 'Qt cache'

  - script: |
      git clone https://github.com/qt/qtbase qtbase --depth=1 --branch=$(QT_BRANCH)
      mkdir -p qtbuild
      cd qtbuild
      ../qtbase/configure -static -nomake examples -prefix $(Build.SourcesDirectory)/qt5 -opensource -confirm-license -opengl desktop --zlib=qt
    condition: ne(variables.WIN_QT_CACHE_RESTORED, 'true')

  - bash: |
      cd qtbuild
      mingw32-make -j2
      mingw32-make install -j2 || cp $(Build.SourcesDirectory)/qtbuild/bin/qmake.exe $(Build.SourcesDirectory)/qt5/bin/qmake.exe
    condition: ne(variables.WIN_QT_CACHE_RESTORED, 'true')
    displayName: 'Build Qt'
