variables:
  qt_branch: 5.15.0

jobs:
- job: QtWasm
  pool:
    vmImage: 'ubuntu-latest'

  variables:
    emsdk_tag: 1.39.13
  timeoutInMinutes: 180
  steps:
  - task: Cache@2
    inputs:
      key: wasm_qt | "$(emsdk_tag)" | "$(qt_branch)"
      path: $(Build.SourcesDirectory)/qt5
      cacheHitVar: WASM_QT_CACHE_RESTORED
    displayName: 'Qt cache'

  - script: |
      nproc
      sudo apt-get update
      sudo apt-get install -y --reinstall ca-certificates
      DEBIAN_FRONTEND=noninteractive sudo apt-get install --no-install-recommends -y pkg-config g++ cmake git python3 python3-distutils xz-utils bzip2 libtool make libicu-dev libxml2 curl libtolua-dev
      git clone https://github.com/emscripten-core/emsdk
      ./emsdk/emsdk install $(EMSDK_TAG)
      ./emsdk/emsdk activate $(EMSDK_TAG)
    displayName: 'Setup Build Environment'

  - script: |
      source ./emsdk/emsdk_env.sh
      git clone https://github.com/qt/qtbase qtbase --depth=1 --branch=$(QT_BRANCH)
      mkdir -p qtbuild
      pushd qtbuild
      ../qtbase/configure -xplatform wasm-emscripten -nomake examples -prefix $(Build.SourcesDirectory)/qt5 -opensource -confirm-license
      make install -j$(nproc)
      popd
    timeoutInMinutes: 120
    condition: ne(variables.WASM_QT_CACHE_RESTORED, 'true')
    displayName: 'Build Qt'

  - script: |
      source ./emsdk/emsdk_env.sh
      mkdir build
      cd build
      emcmake cmake $(Build.SourcesDirectory) -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXE_LINKER_FLAGS_RELEASE=-O3 -DCMAKE_CXX_FLAGS_RELEASE=-O3 -DCMAKE_C_FLAGS_RELEASE=-O3 -DCMAKE_TOOLCHAIN_FILE=$(Build.SourcesDirectory)/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DQt5_DIR=$(Build.SourcesDirectory)/qt5/lib/cmake/Qt5/ -DQt5Widgets_DIR=$(Build.SourcesDirectory)/qt5/lib/cmake/Qt5Widgets -DQt5Gui_DIR=$(Build.SourcesDirectory)/qt5/lib/cmake/Qt5Gui -DQt5Core_DIR=$(Build.SourcesDirectory)/qt5/lib/cmake/Qt5Core -DQt5Network_DIR=$(Build.SourcesDirectory)/qt5/lib/cmake/Qt5Network -DQt5EventDispatcherSupport_DIR=$(Build.SourcesDirectory)/qt5/lib/cmake/Qt5EventDispatcherSupport -DQt5FontDatabaseSupport_DIR=$(Build.SourcesDirectory)/qt5/lib/cmake/Qt5FontDatabaseSupport -DQt5EglSupport_DIR=$(Build.SourcesDirectory)/qt5/lib/cmake/Qt5EglSupport
      emmake make -j$(nproc)
    displayName: 'Build Freeciv'

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)/build'
      contents: 'client/?(*.html|*.data|*.js|*.wasm)'
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: qtwasm

- job: MacOS
  pool:
    vmImage: 'macos-10.14'

  variables:
    macosx_deployment_target: 10.10

  steps:
  - task: Cache@2
    inputs:
      key: macos_qt | "$(qt_branch)" | "$(macosx_deployment_target)"
      path: $(Build.SourcesDirectory)/qt5
      cacheHitVar: MACOS_QT_CACHE_RESTORED
    displayName: 'Qt cache'

  - script: |
      brew install gettext icu4c cmake sdl2_mixer pkg-config
    displayName: 'Setup Build Environment'

  - script: |
      git clone https://github.com/qt/qtbase qtbase --depth=1 --branch=$(QT_BRANCH)
      mkdir -p qtbuild
      pushd qtbuild
      ../qtbase/configure -static -nomake examples -prefix $(Build.SourcesDirectory)/qt5 -opensource -confirm-license
      make install -j$(nproc)
      popd
    timeoutInMinutes: 120
    condition: ne(variables.MACOS_QT_CACHE_RESTORED, 'true')
    displayName: 'Build Qt'

  - script: |
      mkdir build
      cd build
      cmake $(Build.SourcesDirectory) -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_BUILD_TYPE=Release -DICU_DEBUG=true -DIntl_ROOT=/usr/local/opt/gettext -DICU_ROOT=/usr/local/opt/icu4c -DQt5_DIR=$(Build.SourcesDirectory)/qt5/lib/cmake/Qt5 -DQt5Widgets_DIR=$(Build.SourcesDirectory)/qt5/lib/cmake/Qt5Widgets -DQt5Gui_DIR=$(Build.SourcesDirectory)/qt5/lib/cmake/Qt5Gui -DQt5Core_DIR=$(Build.SourcesDirectory)/qt5/lib/cmake/Qt5Core -DQt5Network_DIR=$(Build.SourcesDirectory)/qt5/lib/cmake/Qt5Network -DQt5EventDispatcherSupport_DIR=$(Build.SourcesDirectory)/qt5/lib/cmake/Qt5EventDispatcherSupport -DQt5FontDatabaseSupport_DIR=$(Build.SourcesDirectory)/qt5/lib/cmake/Qt5FontDatabaseSupport
      cp -r * $(Build.ArtifactStagingDirectory)
      make -j2 || true
    displayName: 'Build Freeciv'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: macos

- job: QtWindows
  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - task: Cache@2
    inputs:
      key: win_qt | "$(qt_branch)"
      path: $(Build.SourcesDirectory)/qt5
      cacheHitVar: WIN_QT_CACHE_RESTORED
    displayName: 'Qt cache'

  - script: |
      C:\msys64\usr\bin\pacman -S --noconfirm gettext pkg-config mingw-w64-x86_64-SDL_mixer libcurl-devel mingw-w64-x86_64-icu
    displayName: 'Setup Build Environment'
    env:
      MSYSTEM: MINGW64

  - script: |
      git clone https://github.com/qt/qtbase qtbase --depth=1 --branch=$(QT_BRANCH)
      mkdir -p qtbuild
      cd qtbuild
      ../qtbase/configure -static -nomake examples -prefix $(Build.SourcesDirectory)/qt5 -opensource -confirm-license -opengl desktop --zlib=qt
    condition: ne(variables.WIN_QT_CACHE_RESTORED, 'true')

  - script: |
      mkdir build
      cd build
      cmake $(Build.SourcesDirectory) -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DCURL_ROOT=C:\msys64\usr -DICU_DEBUG=1 -DICU_ROOT=C:\msys64\mingw64 -DQt5_DIR=$(Build.SourcesDirectory)/qt5/lib/cmake/Qt5 -DQt5Widgets_DIR=$(Build.SourcesDirectory)/qt5/lib/cmake/Qt5Widgets -DQt5Gui_DIR=$(Build.SourcesDirectory)/qt5/lib/cmake/Qt5Gui -DQt5Core_DIR=$(Build.SourcesDirectory)/qt5/lib/cmake/Qt5Core -DQt5Network_DIR=$(Build.SourcesDirectory)/qt5/lib/cmake/Qt5Network -DQt5EventDispatcherSupport_DIR=$(Build.SourcesDirectory)/qt5/lib/cmake/Qt5EventDispatcherSupport -DQt5FontDatabaseSupport_DIR=$(Build.SourcesDirectory)/qt5/lib/cmake/Qt5FontDatabaseSupport || true
      mingw32-make -j2 || true
    displayName: 'Build Freeciv'

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)/build'
      contents: '**'
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: win

